name: 🚀 Fastify
run-name: deploy-fastify
on:
  workflow_dispatch:
  push:
    paths:
      - 'packages/fastify/**'
      - 'k8s/fastify/**'

env:
  PACKAGE_NAME: 'fastify'
  REPOSITORY_SUFFIX: 'fastify'
  CI_PROJECT_NAME: 'aws-address-monorepo-fastify' # change it to your own server address
  NODE_VERSION: 20

jobs:
  set-env:
    environment: ${{ (github.ref_name == 'refs/heads/main' || github.ref_name == 'refs/heads/master') && 'production' || 'staging' }}
    runs-on:
      group: gh-runners-self-hosted
    outputs:
      dockerfile: ${{ steps.set.outputs.DOCKERFILE }}
      node_version: ${{ steps.set.outputs.NODE_VERSION }}
      k8s_dir: ${{ steps.set.outputs.K8S_DIR }}
    steps:
      - name: Set envs
        id: set
        run: |
          echo "DOCKERFILE=./packages/${PACKAGE_NAME}/Dockerfile" >> "$GITHUB_OUTPUT"
          echo "NODE_VERSION=${NODE_VERSION}" >> "$GITHUB_OUTPUT"
          echo "K8S_DIR=./k8s/${PACKAGE_NAME}" >> "$GITHUB_OUTPUT"
          echo "PKG_NAME=${PACKAGE_NAME}" >> "$GITHUB_ENV"

  set-env-pkg:
    environment: ${{ (github.ref_name == 'refs/heads/main' || github.ref_name == 'refs/heads/master') && 'address-prod' || 'address-stg' }}
    runs-on:
      group: gh-runners-self-hosted
    env:
      API_KEY: ${{ vars.API_KEY }}
    outputs:
      api_key: ${{ steps.set.outputs.API_KEY }}
    steps:
      - name: Set envs
        id: set
        run: |
          echo "API_KEY=${API_KEY}" >> "$GITHUB_OUTPUT"

  envs-context:
    needs: [set-env, set-env-pkg]
    environment: ${{ (github.ref_name == 'refs/heads/main' || github.ref_name == 'refs/heads/master') && 'production' || 'staging' }}
    runs-on:
      group: gh-runners-self-hosted
    env:
      API_KEY: ${{ needs.set-env-pkg.outputs.api_key }}
    outputs:
      envs-context: ${{ steps.to-json-env.outputs.envs-context }}
    steps:
      - name: Env to JSON
        id: to-json-env
        uses: Base-Repository/actions/env-to-json@main # Change it to your own base repository

  k8s:
    name: "Deploy to k8s"
    needs: [set-env, envs-context]
    uses: Base-Repository/actions/.github/workflows/deploy-to-k8s.yml@main # Change it to your own base repository
    secrets: inherit
    with:
      dry-run: ${{ !(github.event_name == 'workflow_dispatch' || (github.ref_name == 'master' || github.ref_name == 'develop')) }}
      envs-context: ${{ needs.envs-context.outputs.envs-context }}
      dockerfile: ${{ needs.set-env.outputs.dockerfile }}
      context: './'
      k8s-src-dir: ${{ needs.set-env.outputs.k8s_dir }}

